"""update

Revision ID: 1ef0e16339c2
Revises: 751a3f0251cf
Create Date: 2025-06-27 10:11:29.537734

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1ef0e16339c2'
down_revision = '751a3f0251cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unitsystem', 'createdBy',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('unitsystem', 'updatedBy',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unitsystem', 'updatedBy',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('unitsystem', 'createdBy',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###