"""updating unitsystem models

Revision ID: 20b2b709ac0a
Revises: a286e9c58cfb
Create Date: 2025-06-28 17:37:25.902657

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '20b2b709ac0a'
down_revision = 'a286e9c58cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('physicalquantity_unit_system_id_fkey'), 'physicalquantity', type_='foreignkey')
    op.drop_column('physicalquantity', 'unit_system_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('physicalquantity', sa.Column('unit_system_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('physicalquantity_unit_system_id_fkey'), 'physicalquantity', 'unitsystem', ['unit_system_id'], ['id'])
    # ### end Alembic commands ###