"""update4

Revision ID: 2de038a10d9a
Revises: 3c9b3580b353
Create Date: 2025-06-27 10:35:50.850273

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2de038a10d9a'
down_revision = '3c9b3580b353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###