"""update3

Revision ID: 3c9b3580b353
Revises: 8ad1f0d0ba5d
Create Date: 2025-06-27 10:24:08.898993

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3c9b3580b353'
down_revision = '8ad1f0d0ba5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###