"""Creating testtemplate models

Revision ID: 3f68dc9b9b4d
Revises: 4253182a47a1
Create Date: 2025-06-27 18:20:51.442899

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f68dc9b9b4d'
down_revision = '4253182a47a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testtemplate',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('isVLCompatible', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('isLastVersion', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('createdBy', sa.Uuid(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('updatedBy', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testtemplatecondition',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('physicalQuantity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('test_template_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['test_template_id'], ['testtemplate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testtemplategeneralinfo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('isLink', sa.Boolean(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('isFile', sa.Boolean(), nullable=False),
    sa.Column('test_template_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['test_template_id'], ['testtemplate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testtemplatereading',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('physicalQuantity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('isRequired', sa.Boolean(), nullable=False),
    sa.Column('test_template_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['test_template_id'], ['testtemplate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testtemplatereading')
    op.drop_table('testtemplategeneralinfo')
    op.drop_table('testtemplatecondition')
    op.drop_table('testtemplate')
    # ### end Alembic commands ###