"""changing in the unitbase model

Revision ID: 4253182a47a1
Revises: b45b82e5c5c2
Create Date: 2025-06-27 11:38:03.729555

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4253182a47a1'
down_revision = 'b45b82e5c5c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('functionalunit', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('functionalunit', 'createdBy',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('linearunit', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('linearunit', 'createdBy',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('physicalquantity', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('unit', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('unit', 'createdBy',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unit', 'createdBy',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('unit', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('physicalquantity', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('linearunit', 'createdBy',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('linearunit', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('functionalunit', 'createdBy',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('functionalunit', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###