"""updating unitsystem models

Revision ID: 45bf068c57df
Revises: 20b2b709ac0a
Create Date: 2025-06-28 17:43:28.715713

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '45bf068c57df'
down_revision = '20b2b709ac0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###