"""updating ObjectTemplte Models

Revision ID: 4d27c0272e9e
Revises: 45bf068c57df
Create Date: 2025-06-28 19:18:44.220041

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4d27c0272e9e'
down_revision = '45bf068c57df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('functionalunit', sa.Column('base', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('linearunit', sa.Column('base', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('physicalquantity', 'type')
    op.drop_column('physicalquantity', 'based_unit')
    op.add_column('unit', sa.Column('base', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'base')
    op.add_column('physicalquantity', sa.Column('based_unit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('physicalquantity', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('linearunit', 'base')
    op.drop_column('functionalunit', 'base')
    # ### end Alembic commands ###