"""Changing some unitsystem models

Revision ID: 751a3f0251cf
Revises: 20cbdd1cc590
Create Date: 2025-06-27 10:04:06.390634

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '751a3f0251cf'
down_revision = '20cbdd1cc590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###