"""Creating ObjectTemplte Models

Revision ID: 865edea29401
Revises: 25ec94478d4a
Create Date: 2025-06-28 10:24:52.975241

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '865edea29401'
down_revision = '25ec94478d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachmentfilestorage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bucket', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objecttemplate',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allowedComposition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fabricant', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fournisseur', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('isLastVersion', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('createdBy', sa.Uuid(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('updatedBy', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_storage_id', sa.Uuid(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('reference_count', sa.Integer(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('object_template_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['file_storage_id'], ['attachmentfilestorage.id'], ),
    sa.ForeignKeyConstraint(['object_template_id'], ['objecttemplate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objecttemplaterule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('object_template_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('isLink', sa.Boolean(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('isFile', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['object_template_id'], ['objecttemplate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachmentlink',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attachment_id', sa.Uuid(), nullable=False),
    sa.Column('class_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('added_by', sa.Uuid(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('link_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachmentlink')
    op.drop_table('objecttemplaterule')
    op.drop_table('attachment')
    op.drop_table('objecttemplate')
    op.drop_table('attachmentfilestorage')
    # ### end Alembic commands ###