"""update2

Revision ID: 8ad1f0d0ba5d
Revises: 1ef0e16339c2
Create Date: 2025-06-27 10:18:23.471089

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8ad1f0d0ba5d'
down_revision = '1ef0e16339c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###