"""updating unitsystem models

Revision ID: a286e9c58cfb
Revises: aca012a31881
Create Date: 2025-06-28 17:25:08.138104

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a286e9c58cfb'
down_revision = 'aca012a31881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('functionalunit', 'base')
    op.drop_column('functionalunit', 'type')
    op.drop_column('linearunit', 'base')
    op.drop_column('linearunit', 'type')
    op.add_column('physicalquantity', sa.Column('based_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('physicalquantity', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('unit', 'base')
    op.drop_column('unit', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('unit', sa.Column('base', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('physicalquantity', 'type')
    op.drop_column('physicalquantity', 'based_unit')
    op.add_column('linearunit', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('linearunit', sa.Column('base', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('functionalunit', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('functionalunit', sa.Column('base', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###