"""updating unitsystem models

Revision ID: aca012a31881
Revises: d6301e49b242
Create Date: 2025-06-28 17:19:34.092411

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'aca012a31881'
down_revision = 'd6301e49b242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('physicalquantity_functionalunit_link',
    sa.Column('physicalquantity_id', sa.Uuid(), nullable=False),
    sa.Column('functionalunit_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['functionalunit_id'], ['functionalunit.id'], ),
    sa.ForeignKeyConstraint(['physicalquantity_id'], ['physicalquantity.id'], ),
    sa.PrimaryKeyConstraint('physicalquantity_id', 'functionalunit_id')
    )
    op.create_table('physicalquantity_linearunit_link',
    sa.Column('physicalquantity_id', sa.Uuid(), nullable=False),
    sa.Column('linearunit_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['linearunit_id'], ['linearunit.id'], ),
    sa.ForeignKeyConstraint(['physicalquantity_id'], ['physicalquantity.id'], ),
    sa.PrimaryKeyConstraint('physicalquantity_id', 'linearunit_id')
    )
    op.add_column('functionalunit', sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('functionalunit', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('linearunit', sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('linearunit', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint(op.f('physicalquantity_functional_unit_id_fkey'), 'physicalquantity', type_='foreignkey')
    op.drop_constraint(op.f('physicalquantity_linear_unit_id_fkey'), 'physicalquantity', type_='foreignkey')
    op.drop_column('physicalquantity', 'type')
    op.drop_column('physicalquantity', 'value')
    op.drop_column('physicalquantity', 'functional_unit_id')
    op.drop_column('physicalquantity', 'linear_unit_id')
    op.add_column('unit', sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('unit', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'type')
    op.drop_column('unit', 'value')
    op.add_column('physicalquantity', sa.Column('linear_unit_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('physicalquantity', sa.Column('functional_unit_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('physicalquantity', sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('physicalquantity', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('physicalquantity_linear_unit_id_fkey'), 'physicalquantity', 'linearunit', ['linear_unit_id'], ['id'])
    op.create_foreign_key(op.f('physicalquantity_functional_unit_id_fkey'), 'physicalquantity', 'functionalunit', ['functional_unit_id'], ['id'])
    op.drop_column('linearunit', 'type')
    op.drop_column('linearunit', 'value')
    op.drop_column('functionalunit', 'type')
    op.drop_column('functionalunit', 'value')
    op.drop_table('physicalquantity_linearunit_link')
    op.drop_table('physicalquantity_functionalunit_link')
    # ### end Alembic commands ###