"""updating ObjectTemplte Models

Revision ID: d6301e49b242
Revises: e0d9b0bec789
Create Date: 2025-06-28 12:44:11.364769

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd6301e49b242'
down_revision = 'e0d9b0bec789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###