"""updating ObjectTemplte Models

Revision ID: e0d9b0bec789
Revises: 4d2e40c2ff75
Create Date: 2025-06-28 12:23:09.440841

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e0d9b0bec789'
down_revision = '4d2e40c2ff75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###